import { promises as fs } from "node:fs";
import path from "node:path";
import { addProject } from "./registry.mjs";
import { getProjectStatus, runProjectAction } from "./git.mjs";
import { run } from "./command.mjs";
import { appendMemoryEvent, initializeProjectMemory, writeProjectHandoff } from "./memory.mjs";

async function exists(folder) {
  try {
    await fs.access(folder);
    return true;
  } catch {
    return false;
  }
}

async function ensureReadme(projectPath, name) {
  const readme = path.join(projectPath, "README.md");
  if (await exists(readme)) return false;
  await fs.writeFile(readme, `# ${name}\n\nAI workspace initialized by Kevin Sync Console.\n`, "utf8");
  return true;
}

async function isGitRepo(projectPath) {
  const result = await run("git", ["rev-parse", "--is-inside-work-tree"], { cwd: projectPath, timeout: 10000 });
  return result.ok && result.stdout.trim() === "true";
}

async function gitLine(projectPath, args) {
  const result = await run("git", args, { cwd: projectPath, timeout: 10000 });
  return result.ok ? String(result.stdout || "").trim() : "";
}

async function gitLines(projectPath, args, limit = 12) {
  const output = await gitLine(projectPath, args);
  return output.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).slice(0, limit);
}

function agentLabel(agent) {
  if (agent === "codex") return "Codex";
  if (agent === "claude") return "Claude Code";
  if (agent === "glm") return "GLM 5.2";
  return "the next AI tool";
}

export async function generateWorkspaceHandoff(project, targetAgent) {
  const status = await getProjectStatus(project);
  if (!status.exists || (!status.isRepo && !status.isContext)) return "";

  const target = agentLabel(targetAgent);
  const changedFiles = status.isRepo ? await gitLines(status.path, ["status", "--short"], 10) : [];
  const latestCommit = status.isRepo ? await gitLine(status.path, ["log", "-1", "--oneline"]) : "";
  const remoteLine = status.remote ? `Remote: ${status.remote}` : "Remote: none / context-only";
  const branchLine = status.branch ? `Branch: ${status.branch}` : "Branch: not applicable";
  const changeLine = changedFiles.length
    ? `Working tree changes (${changedFiles.length}${changedFiles.length === 10 ? "+" : ""}): ${changedFiles.join("; ")}`
    : "Working tree: clean or not repo-based.";
  const commitLine = latestCommit ? `Latest commit: ${latestCommit}` : "Latest commit: not available.";

  return [
    `Auto-generated handoff for ${target}.`,
    `Project: ${status.name}`,
    `Path: ${status.path}`,
    `${branchLine}`,
    `${remoteLine}`,
    `Sync state: ${status.message || status.state}`,
    `${changeLine}`,
    `${commitLine}`,
    "Memory instruction: read .ai-memory/PROJECT.md, STATUS.md, HANDOFF.md, RULES.md, TASKS.md, and CONTEXT_INDEX.json before making substantial changes.",
    `Next step: continue ${status.name} from the current project state in ${target}. If the console shows red or yellow for this active project, fix that first.`,
    `Generated by AI Sync Console at ${new Date().toISOString()}.`
  ].join("\n");
}

export async function adoptWorkspace(input) {
  const projectPath = path.resolve(input.path);
  const name = input.name?.trim() || path.basename(projectPath);
  await fs.mkdir(projectPath, { recursive: true });

  let initializedGit = false;
  if (!(await isGitRepo(projectPath))) {
    const init = await run("git", ["init"], { cwd: projectPath, timeout: 30000 });
    if (!init.ok) return { ok: false, message: init.stderr || init.message || "Could not initialize local Git." };
    initializedGit = true;
  }

  const createdReadme = await ensureReadme(projectPath, name);
  const project = await addProject({ name, path: projectPath });
  const status = await getProjectStatus(project);
  const memory = await initializeProjectMemory(status);
  await appendMemoryEvent(status, "workspace_adopted", {
    initializedGit,
    createdReadme,
    adoptedFor: "Claude Code and Codex shared workspace"
  });

  return {
    ok: true,
    message: initializedGit ? "Workspace adopted with local Git and memory." : "Workspace adopted with memory.",
    project,
    status: await getProjectStatus(project),
    memory
  };
}

export async function checkpointWorkspace(project, label = "AI workspace checkpoint") {
  const status = await getProjectStatus(project);
  if (!status.exists || !status.isRepo) return { ok: false, message: "Workspace must be an available Git repo first." };
  const commit = await runProjectAction(status, "commitWip");
  if (!commit.ok && !String(commit.message).includes("nothing to commit")) return commit;
  await appendMemoryEvent(status, "workspace_checkpoint", { label });
  return { ok: true, message: "Workspace checkpoint saved.", commit };
}

export async function switchWorkspaceAgent(project, targetAgent, handoffSummary) {
  const status = await getProjectStatus(project);
  if (!status.exists || (!status.isRepo && !status.isContext)) return { ok: false, message: "Workspace or context space must be available first." };
  const summary = handoffSummary?.trim() || await generateWorkspaceHandoff(project, targetAgent);
  const handoff = await writeProjectHandoff(status, summary);
  await appendMemoryEvent(status, "agent_switch", {
    targetAgent,
    handoffSummary: summary,
    generated: !handoffSummary?.trim()
  });
  return {
    ok: true,
    message: `Ready to continue in ${agentLabel(targetAgent)}.`,
    generatedHandoff: summary,
    handoff
  };
}

export async function refreshWorkspaceHandoff(project, targetAgent = "handoff") {
  const status = await getProjectStatus(project);
  if (!status.exists || (!status.isRepo && !status.isContext)) return { ok: false, message: "Workspace or context space must be available first." };
  const summary = await generateWorkspaceHandoff(project, targetAgent);
  const handoff = await writeProjectHandoff(status, summary);
  return {
    ok: true,
    message: "Automatic handoff refreshed.",
    generatedHandoff: summary,
    handoff
  };
}
